In [1]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.1402362 , 0.54281277, 0.61209135],
        [0.08688651, 0.59842301, 0.68486987],
        [0.1862997 , 0.13640603, 0.97026587]],

       [[0.80278476, 0.36778837, 0.14609994],
        [0.93516695, 0.62918984, 0.11801621],
        [0.47532528, 0.16173471, 0.56726646]],

       [[0.79166185, 0.55591382, 0.03970572],
        [0.08228675, 0.51204262, 0.19160559],
        [0.71127857, 0.11830327, 0.52261552]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.63669892, -1.52858467, -1.19813953,  0.57293092, -0.59731533],
       [ 1.01791266,  0.27518175, -0.15412449,  0.76099722,  0.86037693],
       [ 0.85368656,  1.29621762,  0.59054723, -0.19320447,  1.39932935],
       [ 1.58111465, -0.62293349, -0.02418509, -1.41898511, -0.32522638],
       [-1.46603798,  1.53657572, -1.38127497, -1.22574948,  0.02758931]])

# 5. How to find common values between two arrays

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([0, 4, 5])

# 6. How to get the dates of yesterday, today and tomorrow?

In [7]:


yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)



2020-07-25 2020-07-26 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.61296304 0.47135365 0.85991398]
 [0.51983849 0.92752985 0.25282169]
 [0.69927949 0.84613178 0.45406295]]


Array2:
[[0.4166657  0.34008123 0.91120598]
 [0.59051358 0.19373502 0.29424714]
 [0.04543402 0.29076367 0.64428998]]


Equality: False


# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.8972323 , 0.29697074, 0.12546112, 0.71653363, 0.19456461,
       0.00838812, 0.62519041, 0.02571837, 0.74414156, 0.        ])

# 9. How to print all the values of an array?

In [10]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10. Subtract the mean of each row of a matrix

In [11]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 0.48903815, -0.1930593 , -0.29597885],
       [-0.24311789,  0.12230325,  0.12081465],
       [ 0.46058972, -0.3190712 , -0.14151852]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([3., 1., 3., 4., 4.])

# 12. How to get the diagonal of a dot product?

In [13]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([31, 81, 24])

# 13. How to find the most frequent value in an array?

In [14]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[2 5 1 5 6 6 0 3 6 8 9 0 5 1 7 6 3 1 1 0]


1

# 14. How to get the n largest values of an array

In [15]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

6

# 15. How to create a record array from a regular array?

In [16]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])